basePath: /
host: localhost:8000
info:
  contact: {}
  description: API Service for TodoList Application
  title: Todo App Api Service
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
